import keyMirror from 'keymirror';

export default keyMirror({
  REQUEST_LOGIN_USER: null,
  REQUEST_LOGIN_USER_SUCCESS: null,
  REQUEST_LOGIN_USER_ERROR: null,

  REQUEST_SIGNUP_USER: null,
  REQUEST_SIGNUP_USER_SUCCESS: null,
  REQUEST_SIGNUP_USER_ERROR: null,

  AUTO_LOGIN: null,
  LOGOUT_USER: null,

  APP_CONTROLLER_COMPONENT_MOUNTED: null,
  APP_CONTROLLER_COMPONENT_UNMOUNTED: null,
  APP_NEXT_ROUTER_TRANSITION_PATH: null
});
